version: "3.8"
services:
  bank01:
    build:
        context: ./
        dockerfile: ./src/main/java/Bank/Dockerfile
    container_name: Bank_01
    ports:
      - 9000:9000
      - 8000:8000
      - 7000:7000
    environment:
      THIS_BANK_PORT_UDP: "9000"
      THIS_BANK_PORT_TCP: "8000"
      THIS_BANK_PORT_THRIFT: "7000"
    networks:
      BANKING_NET:
        ipv4_address: 172.20.1.1

  bank02:
    build:
      context: ./
      dockerfile: ./src/main/java/Bank/Dockerfile
    container_name: Bank_02
    ports:
      - 9002:9002
      - 8002:8002
      - 7002:7002
    environment:
      THIS_BANK_PORT_UDP: "9002"
      THIS_BANK_PORT_TCP: "8002"
      THIS_BANK_PORT_THRIFT: "7002"
    networks:
      BANKING_NET:
          ipv4_address: 172.20.1.2

  bank03:
    build:
      context: ./
      dockerfile: ./src/main/java/Bank/Dockerfile
    container_name: Bank_03
    ports:
      - 9004:9004
      - 8004:8004
      - 7004:7004
    environment:
      THIS_BANK_PORT_UDP: "9004"
      THIS_BANK_PORT_TCP: "8004"
      THIS_BANK_PORT_THRIFT: "7004"
    networks:
      BANKING_NET:
        ipv4_address: 172.20.1.3


  stock_exchange01:
    build:
        context: ./
        dockerfile: ./src/main/java/StockExchange/Dockerfile
    container_name: StockExchange_01
    ports:
      - 9001:9001
    environment:
      BANK_IP_1: "172.20.1.1"
      BANK_PORT_1: "9000"

      BANK_IP_2: "172.20.1.2"
      BANK_PORT_2: "9002"

      BANK_IP_3: "172.20.1.3"
      BANK_PORT_3: "9004"
    networks:
      BANKING_NET:
        ipv4_address: 172.20.0.2

  webclient:
    build:
      context: ./
      dockerfile: ./src/main/java/Website/Dockerfile-WebClient
    container_name: WebClient
    ports:
      - 6000:80
    depends_on:
      - bank01
    environment:
      BANK_IP_1: "172.20.1.1"
      BANK_TCP_PORT_1: "8000"
      BANK_TCP_PORT_2: "8002"
    networks:
      BANKING_NET:
        ipv4_address: 172.20.2.1

  browser:
    build:
        context: ./
        dockerfile: ./src/main/java/Website/Dockerfile
    container_name: Browser
    depends_on:
      - webclient
    ports:
      - 8080:80
    networks:
        BANKING_NET:
            ipv4_address: 172.20.2.0




networks:
  BANKING_NET:
    name: banking_net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

