version: "3.8"
services:
  bank01:
    build:
        context: ./
        dockerfile: ./src/Bank/Dockerfile
    container_name: Bank_01
    ports:
      - 9000:9000
    networks:
      BANKING_NET:
        ipv4_address: 172.20.0.3

  bank02:
    build:
      context: ./
      dockerfile: ./src/Bank/Dockerfile
    container_name: Bank_02
    ports:
      - 9002:9002
    networks:
      BANKING_NET:
        ipv4_address: 172.20.0.4

  stock_exchange01:
    build:
        context: ./
        dockerfile: ./src/StockExchange/Dockerfile
    container_name: StockExchange_01
    ports:
      - 9001:9001
    environment:
      BANK_IP_1: "172.20.0.3"
      BANK_PORT_1: "9000"

      BANK_IP_2: "172.20.0.4"
      BANK_PORT_2: "9002"
    networks:
      BANKING_NET:
        ipv4_address: 172.20.0.2


networks:
  BANKING_NET:
    name: banking_net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

#version: "3.9"
#
#services:
#  bank:
#    build:
#      context: ./src/Bank
#    volumes:
#      - ./src/Bank:/app
#      - ./src:/src
#    working_dir: /app
#    command: ["java", "Bank"]
#    depends_on:
#      - stock_exchange
#  stock_exchange:
#    build:
#      context: ./src/StockExchange
#    volumes:
#      - ./src/StockExchange:/app
#      - ./src:/src
#    working_dir: /app
#    command: ["java", "StockExchange"]
